### ISSUE TITLE
BALM_paired: embeddings generated from a 1k subsample of the paired test set do not show grouping by V gene

### ISSUE THREAD

**Issue by lsantuari** [brineylab/BALM-paper#1]
Hello,

I cannot reproduce the grouping by V gene for the heavy and the light chain when using a subsample of 1000 sequences from your paired test set and generating the embeddings with the BALM_paired model.
[Here is my notebook.](https://github.com/lsantuari/BALM-paper/blob/93ab53d8ed5a7ecf73448468225e05174c250e35/notebooks/BALM_paired_on_1k_from_test_set.ipynb)

**Update**: The grouping with VH embeddings is clear when considering V gene groups instead of subgroups.

I am closing the issue.

**Comment by kuhaha0629** [comment]
Hello，

could you please share your updated notebook? Thank you very much.
