### ISSUE TITLE
Publication of code and datasets relative to experiments

### ISSUE THREAD

**Issue by ElenaPianfetti** [brineylab/BALM-paper#2]
Hello! Thank you for the interesting paper. I have a few questions regarding the code and datasets used in your experiments.

I noticed that the notebooks available are for training the models and plotting the cross-chain attention. Are you planning to publish the code for the other experiments shown in the paper?
Additionally, in the last paragraph of the results section, you finetune the models for three classification tasks using datasets containing 20,000, 2,000, and 3,000 antibodies. Are these datasets available for public use?

I am interested in using these tasks for comparison with another model and wanted to know if the code and datasets will be made public or if I will need to reimplement them.

Thank you for your time and assistance!

**Comment by smburbach** [comment]
Thanks for reaching out! We're happy to publish the additional code and the classification datasets -- give me a couple of days to get everything together. For the code, is there an experiment/figure you are most interested in, so I can prioritize it for you?

**Comment by ElenaPianfetti** [comment]
I was especially interested in figure 3 and I saw that you have already uploaded the code! Thank you very much for the quick response!

**Comment by smburbach** [comment]
Happy to help! The classification datasets have been uploaded on Zenodo as well: https://zenodo.org/records/12745725
